SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID BETWEEN 100 AND 105;

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN(151,152,153,154,155);

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'P%' OR FIRST_NAME LIKE 'p%';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE 'P%' OR FIRST_NAME LIKE 'p%';

SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '%A' OR FIRST_NAME LIKE '%a';

SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE '__E%';

SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;

SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL;

INSERT INTO employees 
    (employee_id, first_name, last_name, email, phone_number, hire_date, job_id, salary, department_id)
VALUES 
    (207, 'John', 'Doe', 'JDOE', '515.555.1234', SYSDATE, 'IT_PROG', 6000, 60);

SELECT * FROM EMPLOYEES WHERE JOB_ID ='AD_VP' OR  JOB_ID ='IT_PROG';

SELECT * FROM EMPLOYEES ORDER BY LAST_NAME ASC ;

SELECT * FROM EMPLOYEES ORDER BY HIRE_DATE  DESC ;

SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID ASC , SALARY DESC ;

SELECT FIRST_NAME ,LOWER(LAST_NAME ) LASTNAMELOWER ,EMAIL ,JOB_ID ,SALARY  FROM EMPLOYEES ;

SELECT UPPER(FIRST_NAME) FIRSTNAMEUPPER ,LAST_NAME ,EMAIL ,JOB_ID ,SALARY  FROM EMPLOYEES ;

SELECT INITCAP(FIRST_NAME) ,INITCAP(LAST_NAME) FROM EMPLOYEES ; 

SELECT * FROM EMPLOYEES  WHERE LOWER(LAST_NAME ) ='smith';




